<?php

namespace Database\Seeders;

use App\Models\Member;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class MemberSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create sample members with different membership types
        $members = [
            [
                'name' => 'John Smith',
                'email' => 'john.smith@example.com',
                'password' => Hash::make('password123'),
                'phone' => '+1234567890',
                'date_of_birth' => '1985-03-15',
                'gender' => 'male',
                'address' => '123 Main Street',
                'city' => 'New York',
                'state' => 'NY',
                'postal_code' => '10001',
                'country' => 'United States',
                'membership_type' => 'basic',
                'membership_status' => 'active',
                'membership_start_date' => now()->subMonths(6),
                'membership_end_date' => now()->addMonths(6),
                'points_balance' => 150.00,
                'total_spent' => 1250.00,
                'last_login_at' => now()->subDays(2),
                'is_active' => true,
                'email_verified_at' => now()->subMonths(6),
            ],
            [
                'name' => 'Sarah Johnson',
                'email' => 'sarah.johnson@example.com',
                'password' => Hash::make('password123'),
                'phone' => '+1234567891',
                'date_of_birth' => '1990-07-22',
                'gender' => 'female',
                'address' => '456 Oak Avenue',
                'city' => 'Los Angeles',
                'state' => 'CA',
                'postal_code' => '90210',
                'country' => 'United States',
                'membership_type' => 'premium',
                'membership_status' => 'active',
                'membership_start_date' => now()->subMonths(12),
                'membership_end_date' => now()->addMonths(12),
                'points_balance' => 450.00,
                'total_spent' => 3500.00,
                'last_login_at' => now()->subHours(5),
                'is_active' => true,
                'email_verified_at' => now()->subMonths(12),
            ],
            [
                'name' => 'Michael Chen',
                'email' => 'michael.chen@example.com',
                'password' => Hash::make('password123'),
                'phone' => '+1234567892',
                'date_of_birth' => '1988-11-08',
                'gender' => 'male',
                'address' => '789 Pine Street',
                'city' => 'Chicago',
                'state' => 'IL',
                'postal_code' => '60601',
                'country' => 'United States',
                'membership_type' => 'vip',
                'membership_status' => 'active',
                'membership_start_date' => now()->subMonths(18),
                'membership_end_date' => now()->addMonths(18),
                'points_balance' => 1200.00,
                'total_spent' => 8500.00,
                'last_login_at' => now()->subHours(1),
                'is_active' => true,
                'email_verified_at' => now()->subMonths(18),
            ],
            [
                'name' => 'Emily Davis',
                'email' => 'emily.davis@example.com',
                'password' => Hash::make('password123'),
                'phone' => '+1234567893',
                'date_of_birth' => '1992-05-14',
                'gender' => 'female',
                'address' => '321 Elm Street',
                'city' => 'Miami',
                'state' => 'FL',
                'postal_code' => '33101',
                'country' => 'United States',
                'membership_type' => 'basic',
                'membership_status' => 'active',
                'membership_start_date' => now()->subMonths(3),
                'membership_end_date' => now()->addMonths(9),
                'points_balance' => 75.00,
                'total_spent' => 450.00,
                'last_login_at' => now()->subDays(7),
                'is_active' => true,
                'email_verified_at' => now()->subMonths(3),
            ],
            [
                'name' => 'David Wilson',
                'email' => 'david.wilson@example.com',
                'password' => Hash::make('password123'),
                'phone' => '+1234567894',
                'date_of_birth' => '1983-09-30',
                'gender' => 'male',
                'address' => '654 Maple Drive',
                'city' => 'Seattle',
                'state' => 'WA',
                'postal_code' => '98101',
                'country' => 'United States',
                'membership_type' => 'premium',
                'membership_status' => 'active',
                'membership_start_date' => now()->subMonths(9),
                'membership_end_date' => now()->addMonths(15),
                'points_balance' => 320.00,
                'total_spent' => 2800.00,
                'last_login_at' => now()->subDays(1),
                'is_active' => true,
                'email_verified_at' => now()->subMonths(9),
            ],
            [
                'name' => 'Lisa Anderson',
                'email' => 'lisa.anderson@example.com',
                'password' => Hash::make('password123'),
                'phone' => '+1234567895',
                'date_of_birth' => '1995-12-03',
                'gender' => 'female',
                'address' => '987 Cedar Lane',
                'city' => 'Austin',
                'state' => 'TX',
                'postal_code' => '73301',
                'country' => 'United States',
                'membership_type' => 'basic',
                'membership_status' => 'inactive',
                'membership_start_date' => now()->subMonths(24),
                'membership_end_date' => now()->subMonths(12),
                'points_balance' => 25.00,
                'total_spent' => 180.00,
                'last_login_at' => now()->subMonths(3),
                'is_active' => false,
                'email_verified_at' => now()->subMonths(24),
            ],
            [
                'name' => 'Robert Taylor',
                'email' => 'robert.taylor@example.com',
                'password' => Hash::make('password123'),
                'phone' => '+1234567896',
                'date_of_birth' => '1987-01-18',
                'gender' => 'male',
                'address' => '147 Birch Street',
                'city' => 'Denver',
                'state' => 'CO',
                'postal_code' => '80201',
                'country' => 'United States',
                'membership_type' => 'vip',
                'membership_status' => 'active',
                'membership_start_date' => now()->subMonths(15),
                'membership_end_date' => now()->addMonths(21),
                'points_balance' => 950.00,
                'total_spent' => 7200.00,
                'last_login_at' => now()->subHours(3),
                'is_active' => true,
                'email_verified_at' => now()->subMonths(15),
            ],
            [
                'name' => 'Jennifer Brown',
                'email' => 'jennifer.brown@example.com',
                'password' => Hash::make('password123'),
                'phone' => '+1234567897',
                'date_of_birth' => '1991-08-25',
                'gender' => 'female',
                'address' => '258 Spruce Avenue',
                'city' => 'Portland',
                'state' => 'OR',
                'postal_code' => '97201',
                'country' => 'United States',
                'membership_type' => 'premium',
                'membership_status' => 'active',
                'membership_start_date' => now()->subMonths(6),
                'membership_end_date' => now()->addMonths(18),
                'points_balance' => 280.00,
                'total_spent' => 2100.00,
                'last_login_at' => now()->subDays(3),
                'is_active' => true,
                'email_verified_at' => now()->subMonths(6),
            ],
            [
                'name' => 'James Miller',
                'email' => 'james.miller@example.com',
                'password' => Hash::make('password123'),
                'phone' => '+1234567898',
                'date_of_birth' => '1986-04-12',
                'gender' => 'male',
                'address' => '369 Willow Road',
                'city' => 'Boston',
                'state' => 'MA',
                'postal_code' => '02101',
                'country' => 'United States',
                'membership_type' => 'basic',
                'membership_status' => 'suspended',
                'membership_start_date' => now()->subMonths(12),
                'membership_end_date' => now()->addMonths(12),
                'points_balance' => 0.00,
                'total_spent' => 320.00,
                'last_login_at' => now()->subWeeks(2),
                'is_active' => false,
                'email_verified_at' => now()->subMonths(12),
            ],
            [
                'name' => 'Amanda Garcia',
                'email' => 'amanda.garcia@example.com',
                'password' => Hash::make('password123'),
                'phone' => '+1234567899',
                'date_of_birth' => '1993-10-07',
                'gender' => 'female',
                'address' => '741 Poplar Street',
                'city' => 'Phoenix',
                'state' => 'AZ',
                'postal_code' => '85001',
                'country' => 'United States',
                'membership_type' => 'vip',
                'membership_status' => 'active',
                'membership_start_date' => now()->subMonths(21),
                'membership_end_date' => now()->addMonths(27),
                'points_balance' => 1500.00,
                'total_spent' => 12000.00,
                'last_login_at' => now()->subMinutes(30),
                'is_active' => true,
                'email_verified_at' => now()->subMonths(21),
            ],
        ];

        foreach ($members as $memberData) {
            Member::firstOrCreate(
                ['email' => $memberData['email']],
                $memberData
            );
        }
    }
}